"""PassiveDNS log parser.

`passivedns` (Fjellskål) reconstructs DNS question/answer pairs from a capture
and writes them as pipe-delimited records:

    timestamp||src_ip||dst_ip||class||query||qtype||answer||ttl||count
    637.117691||fd2d:ab8c:225::2224||fd2d:ab8c:225::1||IN||www.download.windowsupdate.com.||CNAME||...

It matters here for one reason: the Stratosphere malware captures ship
passivedns alongside their NetFlow, and it is the only source of **real query
names** available to this project. The CTU-13 corpus is NetFlow and carries
none, so without this the DNS tunnelling analyzer could only ever be measured
against traffic generated by the same hand that wrote the detector.

Real benign DNS is the more valuable half of that validation. Any detector
finds a synthetic tunnel; the question that decides whether one is usable is
whether it stays quiet across thousands of real queries to content delivery
networks, telemetry endpoints, certificate status responders and update
services — the traffic no generator reproduces faithfully.

Two format details worth knowing:

**Timestamps are relative to the start of the capture**, not epoch. A
`capture_start` offset is accepted so records can be placed on a real
timeline; the default of zero is harmless, since every measurement this feeds
depends on differences between timestamps rather than their absolute value.

**One question can produce several records** — a CNAME chain emits one line
per hop, all sharing a timestamp. They are kept, because the analyzer measures
distinct query *names*, and each hop is a name the host genuinely resolved.
"""

from __future__ import annotations

from pathlib import Path

import polars as pl

from voidai.ingest.schema import DNS_SCHEMA, conform, empty

_FIELDS = [
    "ts_raw",
    "src_ip",
    "dst_ip",
    "dns_class",
    "query",
    "qtype",
    "answer",
    "ttl",
    "count",
]

#: passivedns writes a banner of `[*] ...` lines before the records.
_COMMENT = "[*]"
_DELIMITER = "||"


def read_passivedns(
    path: str | Path,
    capture_start: float = 0.0,
) -> pl.DataFrame:
    """Parse a passivedns log into the normalised DNS schema.

    The pipe delimiter is two characters, which no CSV reader accepts, so the
    file is split in Python and handed to Polars as a frame. These logs are
    small — hundreds of kilobytes — so the row loop this project avoids
    elsewhere is not worth eliminating here.
    """
    path = Path(path)
    try:
        text = path.read_text(errors="replace")
    except OSError:
        return empty(DNS_SCHEMA)

    rows: list[dict[str, object]] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith(_COMMENT):
            continue

        parts = stripped.split(_DELIMITER)
        if len(parts) < len(_FIELDS):
            continue

        record = dict(zip(_FIELDS, parts[: len(_FIELDS)], strict=True))
        try:
            offset = float(record["ts_raw"])
        except ValueError:
            continue

        rows.append(
            {
                "ts": capture_start + offset,
                "uid": f"{path.stem}:{line_number}",
                "src_ip": record["src_ip"].strip(),
                "dst_ip": record["dst_ip"].strip(),
                # passivedns writes fully-qualified names with a trailing dot.
                "query": record["query"].strip().rstrip("."),
                "qtype": record["qtype"].strip(),
                "rcode": None,
                "answers": record["answer"].strip().rstrip("."),
                "source_file": str(path),
                "source_line": line_number,
            }
        )

    if not rows:
        return empty(DNS_SCHEMA)
    return conform(pl.DataFrame(rows), DNS_SCHEMA).sort("ts")


def load_passivedns(directory: str | Path, capture_start: float = 0.0) -> pl.DataFrame:
    """Read every passivedns log under a directory."""
    directory = Path(directory)
    if not directory.is_dir():
        return empty(DNS_SCHEMA)

    frames = [
        read_passivedns(path, capture_start=capture_start)
        for path in sorted(directory.rglob("*.passivedns"))
    ]
    frames = [f for f in frames if not f.is_empty()]
    if not frames:
        return empty(DNS_SCHEMA)
    return pl.concat(frames, how="vertical").sort("ts")
